### ISSUE TITLE
How to run stage 2?

### ISSUE THREAD

**Issue by rakhimovv** [wangxiaogang866/PIE-NET#2]
Could you please provide instructions how to run stage 2 i.e. parametric inference

`python test_stage_12.py --stage=2`

produces

```
cp: cannot stat 'train.py': No such file or directory
pid: 15000
stage_2
--- Get model and loss
Traceback (most recent call last):
  File "test_stage_12.py", line 498, in <module>
    train()
  File "test_stage_12.py", line 161, in train
    pred_dof_score,all_feat = MODEL.get_stage_2(dof_feat,simmat_feat,dof_mask_pl,proposal_nx_pl,is_training_pl,bn_decay=bn_decay)
  File "/trinity/home/r.rakhimov/new/PIE-NET/models/model.py", line 207, in get_stage_2
    all_feat = tf.concat([dof_feat,simmat_feat_expand],axis = 2)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/array_ops.py", line 1099, in concat
    return gen_array_ops._concat_v2(values=values, axis=axis, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_array_ops.py", line 706, in _concat_v2
    "ConcatV2", values=values, axis=axis, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2958, in create_op
    set_shapes_for_outputs(ret)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2209, in set_shapes_for_outputs
    shapes = shape_func(op)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2159, in call_with_requiring
    return call_cpp_shape_fn(op, require_shape_fn=True)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/common_shapes.py", line 627, in call_cpp_shape_fn
    require_shape_fn)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/common_shapes.py", line 691, in _call_cpp_shape_fn_impl
    raise ValueError(err.message)
ValueError: Dimension 1 in both shapes must be equal, but are 8096 and 4096 for 'concat' (op: 'ConcatV2') with input shapes: [1,8096,512], [1,4096,512], [] and with computed input tensors: input[2] = <2>.
```

**Comment by 2696120622** [comment]
Do you know how to run stage 2?

**Comment by yunfan1202** [comment]
Dave you already solved the problem?
